### ISSUE TITLE
[Bug] Broken legs

### ISSUE THREAD

**Issue by Vsauce07** [LostTrackpad/beatrun-forked#3]
**Describe the bug**
When Beatrun_RunnerHandsOnly is activated, the legs don't work correctly.

**To Reproduce**
1. Go to console
2. Enable Beatrun_RunnerHandsOnly
3. See error

**Expected behavior**
Legs will be bugged and not work correctly.

**Screenshots/Videos**
https://imgur.com/a/u94yttq

**Additional information:**
 - Game Version: Standard
- Mods: no mods enable

**Comment by LostTrackpad** [comment]
I couldn't replicate with no Workshop addons enabled and only Beatrun in the legacy addon folder. You likely have Workshop addons enabled and one or some of them is conflicting with Beatrun, try running the game with the `-noworkshop` launch argument.

(Remember to remove `-noworkshop` once you're done.)

**Comment by LostTrackpad** [comment]
Still can't replicate. Closing.

**Comment by LostTrackpad** [comment]
Replicated this bug, moving tracking this issue to #4. This issue lacked crucial information for bug replication.
